# Generated by Django 5.0.1 on 2024-03-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=30)),
                ('taskname', models.CharField(max_length=15)),
                ('projectname', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
        ),
    ]
